version: '3.9'
services:
  mysql:
    image: quay.io/debezium/example-mysql:2.1
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  debezium-server:
    image: quay.io/debezium/server:2.0
    container_name: debezium-server
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials/gcp_service_account.json
    ports:
      - "8080:8080"
    volumes:
      - ./gcp_service_account.json:/tmp/credentials/gcp_service_account.json
      - ./conf:/debezium/conf
